[package]
name = "auto_default"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
rustversion = "1.0.22"

[dev-dependencies]
trybuild = { version = "1.0.114", features = ["diff"] }
